Compatibility without pcntl extension installed
hyperf/engine-swow pull request #13
Opened 2023-02-01 03:45 UTC by xuanyanwow

2023-02-01 05:51 UTC, huangdijia approved these changes

2023-02-07 01:19 UTC, huangdijia approved these changes

2023-02-07 01:21 UTC, limingxinleo commented on constants.php
> +
这里还需要判断 \Swow\SIgnal 类是否存在，不能直接替换

2023-02-07 01:23 UTC, limingxinleo requested changes

2023-02-07 01:23 UTC, limingxinleo commented on constants.php
> +! defined('SIGBABY') && define('SIGBABY',\Swow\Signal::SYS);
这部分代码需要判断，\Swow\Signal 类是否存在

2023-02-07 01:45 UTC, xuanyanwow commented on constants.php
> +! defined('SIGBABY') && define('SIGBABY',\Swow\Signal::SYS);
已修改

2023-02-07 03:23 UTC, limingxinleo commented
这部分兼容的代码，你是打算用在哪里？

2023-02-07 03:39 UTC, xuanyanwow commented
此前发现的问题，watcher 组件`composer.json`中没有声明依赖 `pcntl` 扩展，导致无法正常运行。

https://github.com/hyperf/watcher/blob/master/src/Watcher.php#L109
https://github.com/hyperf/watcher/blob/master/src/Driver/FswatchDriver.php#L66

@sy-records 给出建议在引擎实现映射
https://github.com/hyperf/hyperf/pull/5348

2023-02-07 03:42 UTC, sy-records commented
😂 我说的也不是映射啊

2023-06-06 05:50 UTC, closed without merging